"""'auto-vote_2'

Revision ID: ea2a89f24d22
Revises: 0a00e98afbfc
Create Date: 2025-01-12 15:51:57.097578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2a89f24d22'
down_revision: Union[str, None] = '0a00e98afbfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('Posts', sa.Column('phone_number', sa.String(), nullable=True))
    op.alter_column('Posts', 'Title',
               existing_type=sa.VARCHAR(),
               nullable=0)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Posts', 'Title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('Posts', 'phone_number')
    
    # ### end Alembic commands ###
