name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu_latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to muhanned
        run: echo "hello Muhanned"
